-- Authentication: application users with BCrypt-hashed passwords. Seeded (dev only) by a runner,
-- not Flyway, since the hash must be generated by the password encoder.
create table users (
    id            bigint generated by default as identity primary key,
    username      varchar(100) not null unique,
    password_hash varchar(100) not null,
    display_name  varchar(255) not null,
    role          varchar(32)  not null,
    created_at    timestamp    not null,
    updated_at    timestamp    not null
);
