-- Finance module, accounts receivable: customers, invoices, invoice lines, payments.
create table customers (
    id                 bigint generated by default as identity primary key,
    name               varchar(255) not null,
    email              varchar(255),
    payment_terms_days int          not null default 30,
    active             boolean      not null default true,
    created_at         timestamp    not null,
    updated_at         timestamp    not null
);

create table invoices (
    id             bigint generated by default as identity primary key,
    customer_id    bigint         not null references customers (id),
    issue_date     date           not null,
    due_date       date           not null,
    status         varchar(32)    not null,
    sales_order_id bigint,
    created_at     timestamp      not null,
    updated_at     timestamp      not null
);

create table invoice_lines (
    id                  bigint generated by default as identity primary key,
    invoice_id          bigint         not null references invoices (id),
    description         varchar(500)   not null,
    quantity            numeric(19, 4) not null,
    unit_price_amount   numeric(19, 4) not null,
    unit_price_currency char(3)        not null,
    created_at          timestamp      not null,
    updated_at          timestamp      not null
);

create table payments (
    id              bigint generated by default as identity primary key,
    invoice_id      bigint         not null references invoices (id),
    amount_amount   numeric(19, 4) not null,
    amount_currency char(3)        not null,
    payment_date    date           not null,
    method          varchar(32)    not null,
    created_at      timestamp      not null,
    updated_at      timestamp      not null
);

create index idx_invoices_status_due on invoices (status, due_date);
create index idx_payments_invoice on payments (invoice_id);
create index idx_payments_date on payments (payment_date);
