-- Finance module, accounts payable: vendors, bills, bill lines, bill payments.
create table vendors (
    id                 bigint generated by default as identity primary key,
    name               varchar(255) not null,
    email              varchar(255),
    payment_terms_days int          not null default 30,
    active             boolean      not null default true,
    created_at         timestamp    not null,
    updated_at         timestamp    not null
);

create table bills (
    id          bigint generated by default as identity primary key,
    vendor_id   bigint      not null references vendors (id),
    issue_date  date        not null,
    due_date    date        not null,
    status      varchar(32) not null,
    created_at  timestamp   not null,
    updated_at  timestamp   not null
);

create table bill_lines (
    id                  bigint generated by default as identity primary key,
    bill_id             bigint         not null references bills (id),
    description         varchar(500)   not null,
    quantity            numeric(19, 4) not null,
    unit_price_amount   numeric(19, 4) not null,
    unit_price_currency char(3)        not null,
    created_at          timestamp      not null,
    updated_at          timestamp      not null
);

create table bill_payments (
    id              bigint generated by default as identity primary key,
    bill_id         bigint         not null references bills (id),
    amount_amount   numeric(19, 4) not null,
    amount_currency char(3)        not null,
    payment_date    date           not null,
    method          varchar(32)    not null,
    created_at      timestamp      not null,
    updated_at      timestamp      not null
);

create index idx_bills_status_due on bills (status, due_date);
create index idx_bill_payments_bill on bill_payments (bill_id);
create index idx_bill_payments_date on bill_payments (payment_date);
