-- HR module: departments, employees, leave requests.
-- Department.manager and Employee.department reference each other, so the manager FK is added
-- after both tables exist.
create table departments (
    id         bigint generated by default as identity primary key,
    name       varchar(255) not null,
    manager_id bigint,
    created_at timestamp    not null,
    updated_at timestamp    not null
);

create table employees (
    id               bigint generated by default as identity primary key,
    name             varchar(255)   not null,
    email            varchar(255),
    department_id    bigint         references departments (id),
    position         varchar(255),
    hire_date        date           not null,
    termination_date date,
    salary_amount    numeric(19, 4),
    salary_currency  char(3),
    status           varchar(32)    not null,
    created_at       timestamp      not null,
    updated_at       timestamp      not null
);

alter table departments
    add constraint fk_departments_manager foreign key (manager_id) references employees (id);

create table leave_requests (
    id          bigint generated by default as identity primary key,
    employee_id bigint      not null references employees (id),
    type        varchar(32) not null,
    start_date  date        not null,
    end_date    date        not null,
    status      varchar(32) not null,
    reviewer    varchar(255),
    decided_at  timestamp,
    created_at  timestamp   not null,
    updated_at  timestamp   not null
);

create index idx_employees_status on employees (status);
create index idx_employees_termination on employees (termination_date);
create index idx_leave_requests_status on leave_requests (status);
create index idx_leave_requests_employee on leave_requests (employee_id);
