-- Building presence: daily check-in / check-out, the basis for the emergency roll-call.
create table building_presence (
    id           bigint generated by default as identity primary key,
    employee_id  bigint      not null references employees (id),
    work_mode    varchar(16) not null,
    check_in_at  timestamp   not null,
    check_out_at timestamp,
    created_at   timestamp   not null,
    updated_at   timestamp   not null
);

create index idx_building_presence_checkin on building_presence (check_in_at);
create index idx_building_presence_open on building_presence (employee_id, check_out_at);
