-- Sales module: leads, opportunities, orders. Customer and owner are referenced by id only
-- (resolved through Finance's CustomerService and HR's EmployeeService), so there are no
-- cross-module foreign keys here — that keeps the modules splittable.
create table leads (
    id             bigint generated by default as identity primary key,
    name           varchar(255) not null,
    company        varchar(255),
    email          varchar(255),
    source         varchar(32),
    status         varchar(32)  not null,
    customer_id    bigint,
    opportunity_id bigint,
    created_at     timestamp    not null,
    updated_at     timestamp    not null
);

create table opportunities (
    id                      bigint generated by default as identity primary key,
    customer_id             bigint         not null,
    owner_employee_id       bigint         not null,
    expected_value_amount   numeric(19, 4) not null,
    expected_value_currency char(3)        not null,
    probability             int            not null,
    expected_close_date     date,
    stage                   varchar(32)    not null,
    previous_stage          varchar(32),
    closed_date             date,
    lost_reason             varchar(500),
    sales_order_id          bigint,
    created_at              timestamp      not null,
    updated_at              timestamp      not null
);

create table sales_orders (
    id                bigint generated by default as identity primary key,
    customer_id       bigint      not null,
    owner_employee_id bigint      not null,
    status            varchar(32) not null,
    order_date        date        not null,
    opportunity_id    bigint,
    invoice_id        bigint,
    created_at        timestamp   not null,
    updated_at        timestamp   not null
);

create table sales_order_lines (
    id                  bigint generated by default as identity primary key,
    order_id            bigint         not null references sales_orders (id),
    description         varchar(500)   not null,
    quantity            numeric(19, 4) not null,
    unit_price_amount   numeric(19, 4) not null,
    unit_price_currency char(3)        not null,
    created_at          timestamp      not null,
    updated_at          timestamp      not null
);

create index idx_opportunities_stage on opportunities (stage);
create index idx_opportunities_closed on opportunities (closed_date);
create index idx_sales_orders_status on sales_orders (status);
