-- Projects module: projects, tasks, milestones, time entries. Customer and employee references are
-- by id only (resolved through Finance/HR services), so no cross-module foreign keys here.
create table projects (
    id                  bigint generated by default as identity primary key,
    name                varchar(255)   not null,
    customer_id         bigint,
    manager_employee_id bigint         not null,
    start_date          date,
    target_end_date     date,
    budget_amount       numeric(19, 4) not null,
    budget_currency     char(3)        not null,
    status              varchar(32)    not null,
    created_at          timestamp      not null,
    updated_at          timestamp      not null
);

create table tasks (
    id                   bigint generated by default as identity primary key,
    project_id           bigint        not null references projects (id),
    title                varchar(500)  not null,
    assignee_employee_id bigint,
    status               varchar(32)   not null,
    due_date             date,
    estimate_hours       numeric(8, 2),
    created_at           timestamp     not null,
    updated_at           timestamp     not null
);

create table milestones (
    id           bigint generated by default as identity primary key,
    project_id   bigint       not null references projects (id),
    name         varchar(255) not null,
    due_date     date,
    completed_at timestamp,
    waived       boolean      not null default false,
    created_at   timestamp    not null,
    updated_at   timestamp    not null
);

create table time_entries (
    id          bigint generated by default as identity primary key,
    task_id     bigint        not null references tasks (id),
    employee_id bigint        not null,
    entry_date  date          not null,
    hours       numeric(5, 2) not null,
    note        varchar(500),
    created_at  timestamp     not null,
    updated_at  timestamp     not null
);

create index idx_projects_status on projects (status);
create index idx_tasks_project on tasks (project_id);
create index idx_tasks_status_due on tasks (status, due_date);
create index idx_milestones_project on milestones (project_id);
create index idx_time_entries_task on time_entries (task_id);
create index idx_time_entries_date on time_entries (entry_date);
